buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  serveCommand: npm run dev -- --port 8080
siteStream:
  id: site-stream
  entityId: SITE_ENTITY_ID
  fields:
    - logo
  localization:
    locales:
      - en
# The ^modules/ header allows access to your modules from other sites
responseHeaders:
  - pathPattern: ^/blogs/.*
    headerKey: aaron-custom-header
    headerValues:
      - aaron-custom-value
  - pathPattern: ^modules/my-module.*
    headerKey: Access-Control-Allow-Origin
    headerValues:
      - "*"
  - pathPattern: ^modules/cors-header-.*
    headerKey: Access-Control-Allow-Origin
    headerValues:
      - "*"
staticRoutes: null
dynamicRoutes:
  - from: /assets/*
    to: /blogs/assets/:splat
    status: 200
